spring:
  profiles:
    group:
      window: windowinfo,common
      dev: devinfo,common
      prod: prodinfo,common
    active: window

---
spring:
  config:
    activate:
      on-profile: windowinfo


  datasource:
    master:
      url: jdbc:mysql://hanghe-database.cla4iewkenyo.ap-northeast-2.rds.amazonaws.com:3306/hanghe?useSSL=false
      username: hanghe
      password: hanghe1212
      driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 8081
  tomcat:
    file-encoding: UTF-8
  servlet:
    #    context-path: /context
    session:
      #      timeout: 10800      # 60*60*3
      timeout: 86400      # 60*60*24


decorator:
  datasource:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: devinfo

#  datasource:
#    #    jndi-name: null
#    url: OX8gM7VWPhTuWFo6bJaSUGn582qhkJX4OiH+RMPoSNt+R2oVNOX/T5gXGwP9nryFg40nr1R8MDQXB4h2w/D2zoQObMPu6ZacsKBQoFXtb6ie22LNXVBc8r+WxCdHiSJW7vSPHvhSb9bQe+ETJ7uW1A==
#    username: cW4mhrJJ24X1Vu5k9dzKEA==
#    password: /3hwiaPoW5nn07QIbeCoSQ==
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    master:
      url: jdbc:mysql://hanghe-database.cla4iewkenyo.ap-northeast-2.rds.amazonaws.com:3306/hanghe?useSSL=false
      username: hanghe
      password: hanghe1212
      driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8081
  tomcat:
    file-encoding: UTF-8
  servlet:
    #    context-path: /context
    session:
      #      timeout: 10800      # 60*60*3
      timeout: 86400      # 60*60*24
    #sweettracker:
    #  tier: testuser
    #  key: testuser
    #  domain: http://trace-api-dev.sweettracker.net:8102/
    #  callback: http://localhost:9080/present/tracking/add/invoice/return

decorator:
  datasource:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prodinfo

#  datasource:
    #    jndi-name: null
#    url: HhfzI7/+RJzLsp9JMjtOk2czuSI5k87/LtLlXnqGbmmJFEbDrKivKVvtrAZTsIk5FGSk1OGBGuRxXLkSRNi8xkuYDZbDyI6xTaYtzjxu70tfiqGkqCGWetQ02NOdvZ9Lm+QEQm5asY+p6/U/bLgFEw==
#    username: cW4mhrJJ24X1Vu5k9dzKEA==
#    password: /3hwiaPoW5nn07QIbeCoSQ==
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    master:
      url: jdbc:mysql://hanghe-database.cla4iewkenyo.ap-northeast-2.rds.amazonaws.com:3306/hanghe?useSSL=false
      username: hanghe
      password: hanghe1212
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
  tomcat:
    file-encoding: UTF-8
    connection-timeout: -1
  servlet:
    session:
      timeout: 86400      # 60*60*24


decorator:
  datasource:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1a8f5d439db80423dcaf8b7b33a82570
            client-secret: lUzvSdLPQT7GKaww2dDBj7dCfijfDUd9
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - account_email
            redirect-uri: http://localhost:8081/user/login/kakao
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
    database: mysql



  servlet.multipart.maxFileSize: 10MB
  servlet.multipart.maxRequestSize: 100MB

  thymeleaf:
    enabled: true
    cache: false

mybatis:
  mapper-locations: mybatis/*.xml
  configuration.map-underscore-to-camel-case: true
  configuration:
    cache-enabled: false
    local-cache-scope: statement

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 10800


logging:
  charset:
    console: UTF-8
    file: UTF-8
